[[glviskit_c]]
arch = "x86_64"
git-tree-sha1 = "b5b23f3664db198fe88cdba3ce51d3999de3b34d"
libc = "glibc"
os = "linux"

    [[glviskit_c.download]]
    sha256 = "2fea79354367ef7f6e714f1879d21e856a9056106a4edbf0db4a256861c7b3c0"
    url = "https://github.com/shadymeowy/glviskit/releases/download/v0.1.3/glviskit_c-x86_64-linux-gnu.tar.gz"
[[glviskit_c]]
arch = "aarch64"
git-tree-sha1 = "6b8aceb073844af1ff18c8ddc5beea014e6ce6e0"
libc = "glibc"
os = "linux"

    [[glviskit_c.download]]
    sha256 = "47de95f75b30266a94af0b1e74bc2347a5812a56191f1f7299b9701ce367a3f9"
    url = "https://github.com/shadymeowy/glviskit/releases/download/v0.1.3/glviskit_c-aarch64-linux-gnu.tar.gz"
[[glviskit_c]]
arch = "x86_64"
git-tree-sha1 = "4107ac09e33dc571af642f59961044db68fedcbb"
libc = "musl"
os = "linux"

    [[glviskit_c.download]]
    sha256 = "a9242f14171f5f803daa6588fadeadeae4b8d9a4885473f5a9348a93014446d6"
    url = "https://github.com/shadymeowy/glviskit/releases/download/v0.1.3/glviskit_c-x86_64-linux-musl.tar.gz"
[[glviskit_c]]
arch = "aarch64"
git-tree-sha1 = "afa6ad53bacef8d5a76feff29317caa957e5b4d1"
libc = "musl"
os = "linux"

    [[glviskit_c.download]]
    sha256 = "5d01b4821bb63eff0b33953b034b913ac0308412916b5f0f50599dcdc106dd76"
    url = "https://github.com/shadymeowy/glviskit/releases/download/v0.1.3/glviskit_c-aarch64-linux-musl.tar.gz"
[[glviskit_c]]
arch = "x86_64"
git-tree-sha1 = "760298a1984aefa54a0aba7702f34441c18a9a86"
os = "macos"

    [[glviskit_c.download]]
    sha256 = "4aca62e87fc0e0a2493dafc8ba4b3f185515cc48b99d4bfecd6d9ed414d4c3b7"
    url = "https://github.com/shadymeowy/glviskit/releases/download/v0.1.3/glviskit_c-x86_64-apple-darwin.tar.gz"
[[glviskit_c]]
arch = "aarch64"
git-tree-sha1 = "5ae1bae0b0dce94690d46c2fcc0da40f8f594641"
os = "macos"

    [[glviskit_c.download]]
    sha256 = "f683e887358010f6fdc73c7844941d0cf86fbfb9d32049d4b46e55374e8c073e"
    url = "https://github.com/shadymeowy/glviskit/releases/download/v0.1.3/glviskit_c-aarch64-apple-darwin.tar.gz"
[[glviskit_c]]
arch = "x86_64"
git-tree-sha1 = "8e8260bf0a71bab37db77c255e221a24c16b9760"
os = "windows"

    [[glviskit_c.download]]
    sha256 = "17a9ce6418713b66cdfb22bec742a286b7259b950e92df9e57203d545501a690"
    url = "https://github.com/shadymeowy/glviskit/releases/download/v0.1.3/glviskit_c-x86_64-w64-mingw32.tar.gz"
