[[glviskit_c]]
arch = "x86_64"
git-tree-sha1 = "ffa21d6283b1c5653d506f25b90bc309e81c9c12"
libc = "glibc"
os = "linux"

    [[glviskit_c.download]]
    sha256 = "799888f1266e80a88ae426f9da759dd73e768ceeae7bd6453aa8db9784a77c98"
    url = "https://github.com/shadymeowy/glviskit/releases/download/v0.1.1/glviskit_c-x86_64-linux-gnu.tar.gz"
[[glviskit_c]]
arch = "aarch64"
git-tree-sha1 = "99d8622bf45b4ca7ec31574fc1adc16facbe234a"
libc = "glibc"
os = "linux"

    [[glviskit_c.download]]
    sha256 = "f3168e16e34392092e66a26d334ed5cd977de550b5ac13e04f4d286d75ceceab"
    url = "https://github.com/shadymeowy/glviskit/releases/download/v0.1.1/glviskit_c-aarch64-linux-gnu.tar.gz"
[[glviskit_c]]
arch = "x86_64"
git-tree-sha1 = "220276c1de8abfee914c748833fdd01f42917bfb"
libc = "musl"
os = "linux"

    [[glviskit_c.download]]
    sha256 = "210c85f5987fd23db15d8b32c632f3db9d6be0b6fd32c4eea3d26a109e56a691"
    url = "https://github.com/shadymeowy/glviskit/releases/download/v0.1.1/glviskit_c-x86_64-linux-musl.tar.gz"
[[glviskit_c]]
arch = "aarch64"
git-tree-sha1 = "8ef3a99c5f6d4f07b2816223f287f67435d0a15c"
libc = "musl"
os = "linux"

    [[glviskit_c.download]]
    sha256 = "a788c4830ef25ea88e070c9660faa70e87184a75bd677ad44207eae6aae1f35a"
    url = "https://github.com/shadymeowy/glviskit/releases/download/v0.1.1/glviskit_c-aarch64-linux-musl.tar.gz"
[[glviskit_c]]
arch = "x86_64"
git-tree-sha1 = "39d86ca7b9e575e41d21912ae9039cfee9f6434a"
os = "macos"

    [[glviskit_c.download]]
    sha256 = "d82b9ad267870c601d350248023d91fa13797cc9fdf54643ddf10a5a11523bca"
    url = "https://github.com/shadymeowy/glviskit/releases/download/v0.1.1/glviskit_c-x86_64-apple-darwin.tar.gz"
[[glviskit_c]]
arch = "aarch64"
git-tree-sha1 = "de00244a770a927cd8dfeb5071c489c83a323f87"
os = "macos"

    [[glviskit_c.download]]
    sha256 = "ff9445a47ef6ebc610d6ec0ca0cae7e3c1e83b2a40956231949357f974b299fb"
    url = "https://github.com/shadymeowy/glviskit/releases/download/v0.1.1/glviskit_c-aarch64-apple-darwin.tar.gz"
[[glviskit_c]]
arch = "x86_64"
git-tree-sha1 = "44b0bdd1089ff8b67797d129b0491eb0854a4eab"
os = "windows"

    [[glviskit_c.download]]
    sha256 = "f3716935a865c1b019b3e62db79b24b201fb73ec94c059c9575b3df5d3e61a46"
    url = "https://github.com/shadymeowy/glviskit/releases/download/v0.1.1/glviskit_c-x86_64-w64-mingw32.tar.gz"
