#!/usr/bin/env python3
"""Generate the baked-in MSDF symbol atlas for glviskit.

Runs msdf-atlas-gen on a monospace font (plus a set of marker codepoints) in
uniform-grid mode, then writes src/symbol_atlas_default.cpp with the RGB pixels
and the grid description so the atlas ships inside the binary. Each symbol is a
fixed-size cell addressed by a flat index (cell = codepoint - first_codepoint
for the contiguous ascii range).

Requires:
  - msdf-atlas-gen on PATH (https://github.com/Chlumsky/msdf-atlas-gen)
  - Pillow  (pip install pillow)

Example:
  python tools/gen_symbol_atlas.py \
      --font /usr/share/fonts/google-noto/NotoSansMono-Regular.ttf
"""

import argparse
import json
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUT = ROOT / "src" / "symbol_atlas_default.cpp"

# marker codepoints packed after the printable ascii cells
DEFAULT_MARKERS = [
    0x25CF,  # black circle
    0x25CB,  # white circle
    0x25A0,  # black square
    0x25B2,  # black up-pointing triangle
    0x25C6,  # black diamond
]


def build_charset(path: Path, markers):
    # printable ascii (space is empty and gets no cell, so start at '!')
    entries = ["[33, 126]"]
    entries += [f"0x{cp:04X}" for cp in markers if cp > 0x7E]
    path.write_text(", ".join(entries), encoding="utf-8")


def run_atlas_gen(font, charset, png, js, pxrange, cell, cols):
    subprocess.run(
        [
            "msdf-atlas-gen",
            "-font", str(font),
            "-charset", str(charset),
            "-type", "msdf",
            "-format", "png",
            "-uniformgrid",
            "-uniformcols", str(cols),
            "-uniformcell", str(cell), str(cell),
            "-uniformorigin", "on",
            "-pxrange", str(pxrange),
            "-size", str(int(cell * 0.85)),
            "-yorigin", "bottom",
            "-imageout", str(png),
            "-json", str(js),
        ],
        check=True,
    )


def load_rgb(png):
    from PIL import Image

    img = Image.open(png).convert("RGB")
    return img.width, img.height, img.tobytes()


def emit_cpp(out, doc, width, height, rgb):
    atlas = doc["atlas"]
    grid = atlas["grid"]
    metrics = doc.get("metrics", {})
    glyphs = doc.get("glyphs", [])
    placed = [g["unicode"] for g in glyphs if "atlasBounds" in g]
    first_cp = min(placed) if placed else 0
    # contiguous ascii cells (markers, all > 126, follow afterwards)
    char_count = sum(1 for cp in placed if cp <= 126)

    # em-units -> cell-units conversion = emSize(px) / cellWidth(px)
    from collections import Counter

    em_px = float(atlas.get("size", grid["cellWidth"]))
    cell_px = float(grid["cellWidth"])
    to_cells = em_px / cell_px

    # monospace advance
    # use the most common so wide markers don't skew it
    advances = [round(g["advance"], 6) for g in glyphs if g.get("advance")]
    adv_em = Counter(advances).most_common(1)[0][0] if advances else 1.0
    advance = adv_em * to_cells
    line_height = float(metrics.get("lineHeight", 1.0)) * to_cells

    lines = []
    lines.append("// Generated by tools/gen_symbol_atlas.py. Do not edit by hand.")
    lines.append("")
    lines.append('#include "glviskit/symbol_atlas.hpp"')
    lines.append("")
    lines.append("namespace glviskit {")
    lines.append("namespace {")
    lines.append("")
    lines.append("const unsigned char kPixels[] = {")
    for i in range(0, len(rgb), 16):
        chunk = rgb[i : i + 16]
        lines.append("    " + "".join(f"0x{b:02X}," for b in chunk))
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace")
    lines.append("")
    lines.append("auto DefaultSymbolAtlas() -> const SymbolAtlasData & {")
    lines.append("    static const SymbolAtlasData data{")
    lines.append(f"        .width = {width},")
    lines.append(f"        .height = {height},")
    lines.append("        .channels = 3,")
    lines.append(f"        .px_range = {float(atlas.get('distanceRange', 0.0))}f,")
    lines.append(f"        .cols = {int(grid['columns'])},")
    lines.append(f"        .rows = {int(grid['rows'])},")
    lines.append(f"        .first_codepoint = {first_cp},")
    lines.append(f"        .char_count = {char_count},")
    lines.append(f"        .advance = {advance}f,")
    lines.append(f"        .line_height = {line_height}f,")
    lines.append("        .pixels = kPixels,")
    lines.append("        .pixel_count = sizeof(kPixels),")
    lines.append("    };")
    lines.append("    return data;")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace glviskit")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--font", required=True, help="path to a (monospace) ttf/otf")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--pxrange", type=float, default=4.0)
    ap.add_argument("--cell", type=int, default=32, help="grid cell size in px")
    ap.add_argument("--cols", type=int, default=16, help="grid columns")
    args = ap.parse_args()

    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        charset = tmp / "charset.txt"
        png = tmp / "atlas.png"
        js = tmp / "atlas.json"
        build_charset(charset, DEFAULT_MARKERS)
        run_atlas_gen(args.font, charset, png, js, args.pxrange, args.cell, args.cols)
        doc = json.loads(js.read_text(encoding="utf-8"))
        width, height, rgb = load_rgb(png)
        emit_cpp(args.out, doc, width, height, rgb)

    g = doc["atlas"]["grid"]
    print(f"wrote {args.out} ({width}x{height}, {g['columns']}x{g['rows']} grid)")


if __name__ == "__main__":
    main()
